run:
  build-tags:
    - unitTests
    - integrationTests
    - journeyTests

linters-settings:
  lll:
    line-length: 180

  wsl:
    allow-cuddle-declarations: true

linters:
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    # Disabled: - godox
    - gofmt
    - goimports
    - golint
    # Disabled: - gomnd
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    # Disabled: interfacer
    - lll
    - maligned
    - misspell
    - nakedret
    - prealloc
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
