linters-settings:
  lll:
    line-length: 180

  wsl:
    allow-cuddle-declarations: true

linters:
  enable:
    - asciicheck
    - bodyclose
    # Disabled: - cyclop
    - deadcode
    - depguard
    - dogsled
    - dupl
    - durationcheck
    - errcheck
    - errorlint
    - exhaustive
    # Disabled: - exhaustivestruct
    - exportloopref
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    # Disabled: - godox
    - goerr113
    - gofmt
    # Disabled: - gofumpt (would be good to turn this on if the "No empty lines before a simple error check" rule could be disabled
    - goheader
    - goimports
    - golint
    # Disabled: - gomnd
    # Disabled: - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ifshort
    - importas
    - ineffassign
    # Disabled: - interfacer
    - lll
    # Disabled: - maligned
    - misspell
    - nakedret
    - nestif
    - nilerr
    # Disabled: - nlreturn
    - noctx
    - nolintlint
    # Disabled: - paralleltest
    - prealloc
    - predeclared
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - structcheck
    - stylecheck
    - testpackage
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - wastedassign
    - whitespace
    # Disabled: - wrapcheck
    - wsl

issues:
  exclude-rules:
    # Allow use of errors.New("...") - match on text until specific code is added as per https://github.com/Djarvur/go-err113/issues/10
    - text: "do not define dynamic errors, use wrapped static errors instead"
      linters: [goerr113]
