run:
  build-tags:
    - unitTests
    - integrationTests
    - journeyTests

linters-settings:
  lll:
    line-length: 180

  wsl:
    allow-cuddle-declarations: true

linters:
  enable:
    - asciicheck
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godot
    # Disabled: - godox
    - goerr113
    - gofmt
    - goimports
    - golint
    # Disabled: - gomnd
    # Disabled: - gomodguard
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    # Disabled: interfacer
    - lll
    - maligned
    - misspell
    - nakedret
    - nestif
    - nolintlint
    - prealloc
    - rowserrcheck
    - scopelint
    - staticcheck
    - structcheck
    - stylecheck
    - testpackage
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - wsl

issues:
  exclude-rules:
    # Allow use of errors.New("...") - match on text until specific code is added as per https://github.com/Djarvur/go-err113/issues/10
    - text: "do not define dynamic errors, use wrapped static errors instead"
      linters: [goerr113]
