version: 1

update_configs:
  - package_manager: go:modules
    directory: /
    update_schedule: daily
    automerged_updates:
      - match:
          dependency_type: all
          update_type: all

  - package_manager: docker
    directory: .batect/app
    update_schedule: daily
    automerged_updates:
      - match:
          dependency_type: all
          update_type: all

  - package_manager: docker
    directory: .batect/build-env
    update_schedule: daily
    automerged_updates:
      - match:
          dependency_type: all
          update_type: all

  - package_manager: javascript
    directory: .batect/honeycomb-fake
    update_schedule: live
    automerged_updates:
      - match:
          dependency_type: all
          update_type: all

  - package_manager: docker
    directory: .batect/push-env
    update_schedule: daily
    automerged_updates:
      - match:
          dependency_type: all
          update_type: all

  - package_manager: docker
    directory: .batect/terraform
    update_schedule: daily
    automerged_updates:
      - match:
          dependency_type: all
          update_type: all
