name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Cache batect
        uses: actions/cache@v1
        with:
          path: ~/.batect/cache
          key: batect-${{ hashFiles('batect') }}

      - name: Cache Golang dependencies
        uses: actions/cache@v1
        with:
          path: .go-cache
          key: golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            golang-

      - name: Download dependencies
        run: ./batect setup

      - name: Build application
        run: ./batect build

      - name: Lint code
        run: ./batect lint

      - name: Run unit tests
        run: ./batect unitTest

      - name: Run journey tests
        run: ./batect journeyTest

      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
