name: Pipeline

on: [push]

jobs:
  build:
    name: "Build, Test and Deploy"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Cache batect
        uses: actions/cache@v1
        with:
          path: ~/.batect/cache
          key: batect-${{ hashFiles('batect') }}

      - name: Cache Golang dependencies
        uses: actions/cache@v1
        with:
          path: .go-cache
          key: golang-${{ hashFiles('go.sum') }}
          restore-keys: |
            golang-

      - name: Download dependencies
        run: ./batect setup

      - name: Build application
        run: ./batect build

      - name: Lint code
        run: ./batect lint

      - name: Check code files have license header
        run: ./batect checkLicenseHeader

      - name: Run unit tests
        run: ./batect unitTest

      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Lint Terraform files
        run: ./batect lintTerraform

      - name: Log in to GCP
        run: ./batect --config-vars-file=batect.prod.yml setupGCPServiceAccount && ./batect --config-vars-file=batect.prod.yml setupGCPBootstrapServiceAccount
        if: github.repository == 'batect/abacus' && github.ref == 'refs/heads/master'
        env:
          GCP_SERVICE_ACCOUNT_EMAIL: githubactions@batect-abacus.iam.gserviceaccount.com
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Setup bootstrapping Terraform
        run: ./batect --config-vars-file=batect.prod.yml setupBootstrapTerraform
        if: github.repository == 'batect/abacus' && github.ref == 'refs/heads/master'

      - name: Import current bootstrapping state
        run: ./batect --config-vars-file=batect.prod.yml importBootstrapState
        if: github.repository == 'batect/abacus' && github.ref == 'refs/heads/master'

      - name: Check bootstrapping state
        run: ./batect --config-vars-file=batect.prod.yml checkBootstrapState
        if: github.repository == 'batect/abacus' && github.ref == 'refs/heads/master'

      - name: Push image
        run: ./batect --config-vars-file=batect.prod.yml pushImage
        if: github.repository == 'batect/abacus' && github.ref == 'refs/heads/master'

      - name: Setup Cloudflare key
        run: ./batect setupCloudflareKey
        if: github.repository == 'batect/abacus' && github.ref == 'refs/heads/master'
        env:
          CLOUDFLARE_KEY: ${{ secrets.CLOUDFLARE_KEY }}

      - name: Setup Terraform
        run: ./batect --config-vars-file=batect.prod.yml setupTerraform
        if: github.repository == 'batect/abacus' && github.ref == 'refs/heads/master'

      - name: Apply Terraform
        run: ./batect --config-vars-file=batect.prod.yml applyTerraform
        if: github.repository == 'batect/abacus' && github.ref == 'refs/heads/master'

      - name: Cleanup
        run: sudo rm -rf .creds .gcloud
