name: Pipeline

on: [push, pull_request]

jobs:
  build:
    name: "Build, Test and Deploy"
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256color
      BATECT_CACHE_TYPE: directory
      BATECT_ENABLE_TELEMETRY: true
      DOCKER_BUILDKIT: 1

    steps:
      - uses: actions/checkout@v2.3.4

      - name: Cache Batect
        uses: actions/cache@v2.1.5
        with:
          path: ~/.batect/cache
          key: batect-${{ hashFiles('batect') }}

      - name: Cache Golang dependencies
        uses: actions/cache@v2.1.5
        with:
          path: .batect/caches/go-cache
          key: golang-${{ hashFiles('go.sum') }}
          restore-keys: |
            golang-

      - name: Download dependencies
        run: ./batect setup

      - name: Build application
        run: ./batect build

      - name: Lint code
        run: ./batect lint

      - name: Check code files have license header
        run: ./batect checkLicenseHeader

      - name: Run unit tests
        run: ./batect unitTest

      - name: Run integration tests
        run: ./batect integrationTest

      - name: Upload coverage to codecov.io
        uses: codecov/codecov-action@v1.4.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: server

      - name: Lint Terraform files
        run: ./batect --config-vars-file=batect.prod.yml lintTerraform

      - name: Log in to GCP
        run: ./batect --config-vars-file=batect.prod.yml setupGCPServiceAccount
        if: github.repository == 'batect/abacus' && github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          GCP_SERVICE_ACCOUNT_EMAIL: github-actions@batect-abacus-prod.iam.gserviceaccount.com
          GCP_SERVICE_ACCOUNT_KEY: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Push image
        run: ./batect --config-vars-file=batect.prod.yml pushImage
        if: github.repository == 'batect/abacus' && github.ref == 'refs/heads/main' && github.event_name == 'push'

      - name: Setup Cloudflare key
        run: ./batect --config-vars-file=batect.prod.yml setupCloudflareKey
        if: github.repository == 'batect/abacus' && github.ref == 'refs/heads/main' && github.event_name == 'push'
        env:
          CLOUDFLARE_KEY: ${{ secrets.CLOUDFLARE_KEY }}

      - name: Setup Terraform
        run: ./batect --config-vars-file=batect.prod.yml setupTerraform
        if: github.repository == 'batect/abacus' && github.ref == 'refs/heads/main' && github.event_name == 'push'

      - name: Apply Terraform
        run: ./batect --config-vars-file=batect.prod.yml applyTerraform
        if: github.repository == 'batect/abacus' && github.ref == 'refs/heads/main' && github.event_name == 'push'

      - name: Run smoke test
        run: ./batect --config-vars-file=batect.prod.yml smokeTest
        if: github.repository == 'batect/abacus' && github.ref == 'refs/heads/main' && github.event_name == 'push'

      - name: Cleanup credentials
        run: sudo rm -rf .creds .gcloud

